name: qrcode
description: A flutter plugin for scanning QR codes. Use AVCaptureSession in iOS and zxing in Android.
version: 2.0.0
# author: chendaxin <dxchen321@gmail.com>
homepage: https://github.com/SiriDx/qrcode

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.qrcode
        pluginClass: QrcodePlugin

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec